format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$nodejs\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

#

add_newline = false

[fill]
symbol = ' '

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "
style = "bold bright-green"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"dotfiles" = "󰲋"

[python]
symbol = '  '
#style = 'fg:white bg:purple'
style = 'bright-yellow'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = false
pyenv_prefix = ""

[aws]
symbol = ' '
style = 'bright-yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold yellow"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold yellow"

[cmd_duration]
#min_time = 500
style = 'fg:white'
format = '[$duration]($style)'


[os]
disabled = false
style = "crust"

[nodejs]
symbol = " "
style = "bright-green"
#format = '[[ $symbol( $version) ]()]($style)'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
detect_files = ["package.json", "package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

#[python]
#symbol = ""
#style = "bg:green"
#format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = false

